# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Antonio López Marín"
description: > # this means to ignore newlines until "email:"
    Student of Computer Science in Polytechnic University of Valencia

email: tonilopezmr@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Antonio López Marín'
author: 'Antonio López'
author_image: "/assets/images/autor_logo.jpg"

paginate:	5

url: "http://tonilopezmr.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@tonilopezmr'

#fill in disqus shortname to use disqus
disqus: tonilopezmr

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/tonilopezmr
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/tonilopezmr
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:  linkedin
    url:   https://www.linkedin.com/in/tonilopezmr
    desc:  See my profile
    share_url:
    share_title:
    share_link:

  - icon:  envelope
    url: mailto:tonilopezmr@gmail.com
    desc:  Send me an email
    share_url:
    share_title:
    share_link:


#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
